name: Check Markdown links

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        env:
          FILE_EXTENSION: .md,.mdx
      - name: LIVE Broken Link Check
        uses: technote-space/broken-link-checker-action@v1
        env:
          TARGET: https://docs.kintohub.com/
